# Generated by Django 5.1.4 on 2024-12-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="current_page",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="total_pages",
            field=models.IntegerField(default=0),
        ),
    ]
