# Generated by Django 5.1.4 on 2024-12-12 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_book_current_page_book_total_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="current_page",
        ),
        migrations.RemoveField(
            model_name="book",
            name="total_pages",
        ),
        migrations.CreateModel(
            name="BookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_page", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.book"
                    ),
                ),
            ],
        ),
    ]
