# Generated by Django 5.1.4 on 2024-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_book_user_alter_reader_user_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
