# Generated by Django 5.1.4 on 2024-12-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_reader_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="profile_picture",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="profile_pictures/")),
                (
                    "profile_picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.reader"
                    ),
                ),
            ],
        ),
    ]
