# Generated by Django 5.1.4 on 2024-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_remove_reader_profile_picture_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
