# Generated by Django 5.1.4 on 2024-12-12 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_reader_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="user",
            new_name="reader",
        ),
    ]
